### ISSUE TITLE
Email não é unico

### ISSUE THREAD

**Issue by StellaThimoty** [felipez3r0/workshop-node-ts-intro#12]
No arquivo `user.entity.ts` a coluna `@Column() email!: string` não possui o atributo unique, permitindo o cadastro de dois usuários com o mesmo email

Nesta ocorrência, um usuário pode acessar tasks de outro usuário ao logar, além de ser melhor ter emails como algo único

**Comment by felipez3r0** [comment]
Resolvida na etapa 12 :+1:
